version: "3"
services:
  hub:
    image: selenium/hub:4.18.1-20240224
  chrome:
    image: selenium/node-chrome:4.18.1-20240224
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 0
    env_file: .env
  firefox:
    image: selenium/node-firefox:4.18.1-20240224
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 0
    env_file: .env