version: "3"
services:
  vendor-portal:
    image: amitdocker369/selenium
    environment:
    # we can keep below line as '- BROWSER' since we have BROWSER in .env file and Jenkins will assume BROWSER=${BROWSER} 
    # if the parameter is missing below
    - BROWSER=${BROWSER}
    - HUB_HOST=hub    
    - THREAD_COUNT=1
    - TEST_SUITE=vendor-portal.xml
    volumes:
    - ./output/vendor-portal:/home/selenium-docker/test-output
  flight-reservation:
    image: amitdocker369/selenium
    environment:
    - BROWSER=${BROWSER}
    - HUB_HOST=hub    
    - THREAD_COUNT=1
    - TEST_SUITE=flight-reservation.xml
    volumes:
    - ./output/flight-reservation:/home/selenium-docker/test-output